name: tests

on:
    push:
    pull_request:

jobs:
    tests:

        runs-on: ubuntu-latest

        strategy:
            fail-fast: true
            matrix:
                php: [ 7.2, 7.3, 7.3, 7.4, 8.0 ]
                stability: [prefer-lowest, prefer-stable]

        name: P${{ matrix.php }}

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  tools: composer:v2
                  coverage: none

            - name: Validate composer.json and composer.lock
              run: composer validate

            - name: Install dependencies
              run: composer update --prefer-dist --no-interaction --no-progress

            - name: Execute tests
              run: vendor/bin/phpunit --verbose
